# Generated by Django 6.0 on 2025-12-16 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('familiya', models.CharField(max_length=200)),
                ('jami_yozilgan_kitoblar_soni', models.CharField(max_length=200)),
                ('millati', models.CharField(max_length=200)),
                ('yoshi', models.IntegerField(blank=True, default=0, null=True)),
                ('yatilgan_vaqt', models.DateField(auto_now_add=True)),
                ('ozgargan_vaqt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('varoqlar_soni', models.IntegerField()),
                ('jild', models.CharField(choices=[('qattiq', 'Qattiq muqova'), ('yumshoq', 'Yumshoq muqova')], max_length=200)),
                ('rasm', models.ImageField(upload_to='media/')),
                ('omborda_mavjud', models.BooleanField(default=0)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('ozgartirilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=200)),
                ('jami_sotilgan_kitoblar_soni', models.IntegerField(default=0)),
                ('yaratilgan_vaqt', models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now)),
                ('ozgartirilgan_vaqt', models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now)),
                ('sotiladigan_kitoblar', models.ManyToManyField(to='book.book')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
